FROM nginx:1.25.2

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        python3 python3-pip tshark iproute2 procps && \
    pip3 install psutil --break-system-packages --no-cache-dir && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo 'wireshark-common wireshark/install-setuid boolean true' | debconf-set-selections && \
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure wireshark-common

WORKDIR /root
