FROM kalilinux/kali-last-release

RUN if [ -f /etc/apt/sources.list.d/kali.sources ]; then \
        sed -i 's/https/http/g' /etc/apt/sources.list.d/kali.sources; \
    fi && \
    echo 'Acquire::https::Verify-Peer "false";' > /etc/apt/apt.conf.d/99verify-peer.conf && \
    echo 'Acquire::AllowInsecureRepositories "true";' >> /etc/apt/apt.conf.d/99verify-peer.conf && \
    echo 'Acquire::AllowDowngradeToInsecureRepositories "true";' >> /etc/apt/apt.conf.d/99verify-peer.conf

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        python3 python3-pip curl iproute2 procps iptables tshark debconf-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo 'wireshark-common wireshark/install-setuid boolean true' | debconf-set-selections && \
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure wireshark-common

RUN pip3 install h2 httpx[http2] --break-system-packages --no-cache-dir

WORKDIR /root

COPY attacker_multi.py           /root/
COPY attacker_single.py          /root/
COPY detector.py                 /root/
COPY detector_window.py          /root/
COPY ips_blocker.py              /root/
COPY client_traffic.py           /root/
COPY client_advanced.py          /root/
COPY client_burst.py             /root/
COPY client_normal_adjustable.py /root/
